### ISSUE TITLE
R support?

### ISSUE THREAD

**Issue by lf-araujo** [CDSoft/pp#43]
Are there any plans for R programming language support? R allows for very complex graphic capabilities and would be a nice addition!

Thanks

**Comment by tajmone** [comment]
Usually language definitions are contributed by users who need them. In order to create a language definition one needs to know the language at hand, so being an R programmer is a prerequisite to create a good Highlight langdef for R.

You could give it a try and create an R langdef yourself. All you really need to know is how to write Regular Expressions, and then look at existing language definitions as reference examples. Writing langdefs is not difficoult, and you'll surely find amongst the existing definitions one that is similar/close to R, and can use that as a starting point. But without some knowledge of R's syntax, it would be like working in the dark.

Since R is open source, you could create a script that extracts the language keywords from the source files, and then inject them into the R langdef via some template. Iideally, this should be done in R itself since often (but not always) it's enough to just import the file that defines the language's syntax tokens for the parser, and then manipulate those string vars to build a keyword lists from them. This would make maintainance of the langdef easier, as it would allow to automatically integrate new keywords when the language changes (if it does).

Peeking at R's sources (the language parser) will allow you to find not only the list of keywords, but probably also the various RegEx that you'll need in your langdef (ie: patters for labels, comments, numbers, etc.)

Experience with R would also be required for this task in order to handle language version changes — Eg: in order to cover both code for older and newer releases of R, you might want to include also deprecated/removed keywords (if any). Since the purpose of an HL langdef is to beautify source code (which is expected to be valid code), you want to cover all possible version of each language (unlike editors, where code completion should stick to a specific version of any language, and not suggest deprecated keywords).

But of course, you could start with a simple R definition, and then revise and polish it in the course of time — which is the route that langdefs usually take, since edge cases tend to come to attention only with extensive use of a language definition.

**Comment by lf-araujo** [comment]
Thanks, will try to create one for R and report back...

**Comment by tajmone** [comment]
Ooops, I apolgyse. I got confused with my answer (I was answering different notifications at once and got confused with the pendfing notification on syntax highlighters thread). Sorry, lack of sleep and multi-task coffee-frenzic attitude.

What you mean by R support in PP? PP is language agnostic, it's just a macro preprocessor (written in Haskell).

**Comment by CDSoft** [comment]
Just to clarify things. pp uses graphviz and plantuml to produce diagrams from a simple text file embedded in a markdown document. In the output, the source of the diagram is replaced by an image.
I'll soon add a support for Asymptote.

R may be a bit more complex because I guess it can do much more than just producing an image.

What kind of usage would like?

- generate an image from a script? (as graphviz or plantuml)
- execute a more generic R script? (as python scripts) In this case you would have to handle its output yourself.

In both case it is possible to add R support. In fact you can already call R scripts as shell scripts (not tested!):

    !sh
    ~~~~~
    #!/usr/bin/Rscript --slave
    ....
    ~~~~~

**Comment by lf-araujo** [comment]
Thanks,

Two functionalities:

1. Run a script and capture all text (so to source into a mardkown document);
2. Run a script and capture the image from the R device.

Best,
lf

**Comment by CDSoft** [comment]
Could you please give small examples (scripts and command lines) for both functionalities?

**Comment by lf-araujo** [comment]
Absolutelly,

Here is a small example using knitr. The code I enter within the block gets printed at the pdf as well:


```
```{r lm}
model = lm(dist~speed,data = cars)
summary(model)
```


Produces:

```
Call:
lm(formula = dist ~ speed, data = cars)

Residuals:
    Min      1Q  Median      3Q     Max 
-29.069  -9.525  -2.272   9.215  43.201 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) -17.5791     6.7584  -2.601   0.0123 *  
speed         3.9324     0.4155   9.464 1.49e-12 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 15.38 on 48 degrees of freedom
Multiple R-squared:  0.6511,	Adjusted R-squared:  0.6438 
F-statistic: 89.57 on 1 and 48 DF,  p-value: 1.49e-12
```

The code below is executed with knitr and printed out as a graph:

```
```{r pressure, echo=FALSE, fig.cap='test plot'}
plot(pressure)
```
![image](https://user-images.githubusercontent.com/10139950/32267525-a9daed64-bf3f-11e7-8523-c7748997261c.png)

**Comment by CDSoft** [comment]
Ok. The first example could be implemented as a script macro that calls `Rscript --slave`.

The second example, called with `Rscript --slave` produces a PDF file (`Rplots.pdf`). Do you know how to change the name and the format of the output?

**Comment by lf-araujo** [comment]
Thanks for the interest. A quick investigation and I found a possible approach. If you have R installed, send the following to bash (or run in the command line):

`Rscript -e 'pdf("foo.pdf");  plot(cumsum(rnorm(100)), type="l");  dev.off()'
`
This will generate a foo.pdf with a nice figure that pandoc will be able to import.  Other functions exists as well, but they are not in base R (png(), jpeg(), and so on)... I am almost sure pandoc can handle pdfs as figures for latex output, less sure about other formats...

**Comment by CDSoft** [comment]
`Rscript -e 'png("foo.png"); plot(cumsum(rnorm(100)), type="l");'` produces a PNG image.

This could be executed by a `Rplot` macro:

    !Rplot(foo)
    ~~~~
    plot(cumsum(rnorm(100)), type="l");
    ~~~~

The `Rscript` will just execute a script and print its output.

**Comment by CDSoft** [comment]
I have added both `!Rscript` and `!Rplot` to the last release (2.1.2).

**Comment by lf-araujo** [comment]
Thank you so much. Will test it, as soon as I can!

I will try to incorporate pp into my pandoc building system with [make](https://lf-araujo.github.io/2017/08/14/mmv1.html).

Best,
lf

**Comment by lf-araujo** [comment]
Tested, both work as expected in Ubuntu 17.04. Thank you.

It would be an extra if I were able to pass {width = 30%} to the figure environment as per the other issue I opened.

You may want to close this issue.

**Comment by CDSoft** [comment]
With diagrams macros you can pass the attributes with the image name:

    !Rplot(IMAGE{attributes})(LEGEND)(GRAPH DESCRIPTION)

e.g.

    !Rplot(img/foo{width=30%})(legend...)(R script...)

**Comment by geniusupgrader** [comment]
@CDSoft please close issues, whenever possible
