### ISSUE TITLE
Ditaa svg support

### ISSUE THREAD

**Issue by rudolph9** [CDSoft/pp#88]
Ditaa now has support for outputting svgs

```
    --svg                       Write a SVG image as destination file.
```

https://github.com/stathissideris/ditaa

Could we make this the default for processing ditaa or perhaps is there a way to set it as the default?

**Comment by CDSoft** [comment]
I'll do it.

**Comment by CDSoft** [comment]
done. Try pp 2.13.

**Comment by rolandog** [comment]
Hi.

Just to add some feedback, Ubuntu and Debian seem to still have release version `0.10+ds1-1.2` of `ditaa` (instead of the more recent 0.11), which results in a failure when the task _checking .stack-work/pp-test.output_ is performed:

```
diff -b -B .stack-work/pp-test.output test/pp-test.ref of `make test` 
1,10d0
< 
< ditaa version 0.11, Copyright (C) 2004--2017  Efstathios (Stathis) Sideris
< 
< Running with options:
< overwrite
< encoding = UTF-8
< svg
< Reading file: .stack-work/img/ditaa-test.txt
< Rendering to file: .stack-work/img/ditaa-test.svg
< Done in 0sec
make: *** [Makefile:200: test-md] Error 1
```

I've filed a bug in Ubuntu, and another in Debian (which I'm waiting confirmation).

Here's the link for the bug report in LaunchPad:

https://bugs.launchpad.net/bugs/1886193
